# Generated by Django 5.2.8 on 2025-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
